---
name: sql-formatter-bun
description: A whitespace formatter for different query languages.
homepage: https://sql-formatter-org.github.io/sql-formatter/
licenses:
  - MIT
languages:
  - SQL
categories:
  - Formatter

source:
  id: pkg:npm/github:h-yasha/sql-formatter-bun

bin:
  sql-formatter: npm:sql-formatter
