---
name: sql-formatter-bun
description: A whitespace formatter for different query languages. bun. bun. bun.
homepage: https://sql-formatter-org.github.io/sql-formatter
licenses:
  - MIT
languages:
  - SQL
categories:
  - Formatter

source:
  id: pkg:github/h-yasha/sql-formatter-bun@2fda3622f1cfe501408359c8b5ef9b1e7e7d3a8f
  build:
    run: |
      bun install --production

bin:
  sql-formatter: bin:bin/sql-formatter-cli.ts
